### ISSUE TITLE
XAML WPF don't show 

### ISSUE THREAD

**Issue by Brouilles** [Extrimis/InteropCompositor#1]
The XAML code don't show over the compositor. A way to fix it? I use your sample project.

**Comment by Brouilles** [comment]
Airspace Issue. I saw your comment here in the README about it https://github.com/Extrimis/Win32-Acrylic-Effect

**Comment by Extrimis** [comment]
The only way currently we have is by overlapping windows, i mean creating two window, draw composition stuff on to one window and use the other window to draw wpf content. and overlap wpf window on top of composition window using setwindowpos() however you will lose the animations. and also make wpf window transparent, you can use SetWindowCompositionAttribute() with INVALID_STATE accent policy for that, it will create a window similar to WS_EX_NOREDIRECTION_BITMAP

**Comment by Brouilles** [comment]
I see. Not ideal. I don't understand why Microsoft has removed the dwmapi trick in the last Insider Build.

**Comment by Extrimis** [comment]
I have been working on a C# WPF project to bring acrylic in to WPF apps, to avoid the airspace issue i used the overlapping and clipping method, the results look better than SetWindowCompositionAttribute() acrylic, this one will not flicker during window resize and you can adjust the blur amount, saturation, noise etc.. What it does is create a full scree wide window to draw the acrylic and use Rectangle clip to clip the acrylic according to the size of the window on top of it (Overlapping Windows). This airspace issue is so annoying, even microsoft refuse to fix it.

**Comment by Brouilles** [comment]
Interesting. Do you have a sample? Not a problem in multiple screen scenario? With different ratios?

**Comment by Extrimis** [comment]
Yes sure, check this out :
[acrylic demo .NET 5.zip](https://github.com/Extrimis/InteropCompositor/files/7576141/acrylic.demo.NET.5.zip)

**Comment by Extrimis** [comment]
I haven't checked wit multi monitor setup, this is just a demo version that i am abuilding.

**Comment by Brouilles** [comment]
So just no effect on second screen.
![image](https://user-images.githubusercontent.com/1573282/142760732-8660579d-0b0f-4d5a-b6e6-d6e6d84747c8.png)

**Comment by Extrimis** [comment]
I am still working on it, it is because the composition host width doesn't change based on screen size, for each system the number of monitors differ and the DPI also changes i am trying to fix it i can make the composition host with a predefined width like a large number, but to make it more reliable i need to add some other features like auto resize based on screen resolution and dpi changes.

**Comment by Extrimis** [comment]
https://user-images.githubusercontent.com/72641365/142760860-a4aebbd1-3804-4c34-baf5-fd30e16fd366.mp4

i am also trying to use reveal effect for window borders.
