### ISSUE TITLE
Supports for WinUI3

### ISSUE THREAD

**Issue by linhnddev** [Extrimis/InteropCompositor#2]
I have tried this on WinUI3 project and it throws an exception when trying to assign a Visual to ICompositionTarget.Root.

For exanple:

// begin sample code

 _compositor = new Compositor();
 ICompositorDesktopInterop interop = _compositor.As<ICompositorDesktopInterop>();
 interop.CreateDesktopWindowTarget(_mhwnd, false, out var target);
 _mTarget = (ICompositionTarget) target;

 _mRoot = _compositor.CreateContainerVisual();
_mTarget.Root = _mRoot;

var test  =_mTarget.Root.Size;

// end sample code

The exception "System.InvalidCastException: 'Unable to cast object of type 'System.__ComObject' to type 'Windows.UI.Composition.Visual'.'" throwed at the line "var test  =_mTarget.Root.Size;"

Tried customizing on my own. Tried Marshal with no luck. Could you fix it? Thanks so much!

**Comment by Extrimis** [comment]
Are you using WinUI 3? I actually designed it for WPF-based projects. If you are using WinUI, what is the requirement for using Windows.UI.Composition.Visual? You can render directly into a Microsoft.UI.Composition.Visual without even using this library. I can help if you specify your requirements more clearly.

**Comment by linhnddev** [comment]
WinUI 3 supports  Microsoft.UI.Composition.Visual. But I need to use some Window APIs from win32 (which I can fully customized) and add some visuals on it since WinUI 3 AppWindow API is not open enough.Tried your lib but got no exception but not able to render any visuals. I have tried to reproduce and got exception on this line "var test =_mTarget.Root.Size;" as I have described above. I have tried to create my own ComImport but no luck, don't know what I'm missing. Hope that you can help. Thanks in advanced!

**Comment by linhnddev** [comment]
Thanks for your reply! I've created a sample project here:
https://github.com/linhnddev/WinUI3CompositionInterop

**Comment by Extrimis** [comment]
I think _mTarget.Root.Size is not accessible anymore. you should set some size for the root visual by yourself. usually I use the window width and height itself. anyway rendering operations are working fine, I tried bringing the window to front and drawn a sprite visual on it and it seems to be working.
![image](https://user-images.githubusercontent.com/72641365/226152561-a53f5426-19e3-4d05-b04e-dbf870a125ea.png)

**Comment by linhnddev** [comment]
Tks for your reply! Can I have the code that you used?

**Comment by linhnddev** [comment]
Thanks so much!
